{
  "openapi": "3.0.3",
  "info": {
    "title": "Movie Api",
    "description": "API for Movies",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3001"
    }
  ],
  "tags": [
    {
      "name": "Users",
      "description": "Managing users"
    },
    {
      "name": "Movies",
      "description": "Retrieving Movies"
    },
    {
      "name": "Bookmarks",
      "description": "Managing Boomarks"
    }
  ],
  "paths": {
    "/api/auth/register": {
      "post": {
        "tags": ["Users"],
        "summary": "Register",
        "description": "Creating a new user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The newly created user's id, image and token",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "id": {
                      "type": "string",
                      "example": "6516832f3bdaa5d3e07a4db5"
                    },
                    "token": {
                      "type": "string",
                      "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2ODMyZjNiZGFhNWQzZTA3YTRkYjUiLCJ1c2VybmFtZSI6ImRhdmlkMDA3IiwiaWF0IjoxNzAwNjQwNTMyLCJleHAiOjE3MDMyMzI1MzJ9.sZyKqQmJi5HLrbqZHaMIli6jBvCoVn4gq7bXu-F3j8M"
                    },
                    "image": {
                      "type": "string",
                      "example": "https://res.cloudinary.com/demmgc49v/image/upload/v1697220616/movie-app/tmp-5-1697220613691_r6v9fs.jpg"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Email or password not provided"
          },
          "500": {
            "description": "Something went wrong on the server"
          }
        }
      }
    },
    "/api/auth/login": {
      "post": {
        "tags": ["Users"],
        "summary": "Login",
        "description": "Logging in an already registered user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "JacobIsaac@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "007007"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The logged in user's id, image and token",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "id": {
                      "type": "string",
                      "example": "6516832f3bdaa5d3e07a4db5"
                    },
                    "token": {
                      "type": "string",
                      "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2ODMyZjNiZGFhNWQzZTA3YTRkYjUiLCJ1c2VybmFtZSI6ImRhdmlkMDA3IiwiaWF0IjoxNzAwNjQwNTMyLCJleHAiOjE3MDMyMzI1MzJ9.sZyKqQmJi5HLrbqZHaMIli6jBvCoVn4gq7bXu-F3j8M"
                    },
                    "image": {
                      "type": "string",
                      "example": "https://res.cloudinary.com/demmgc49v/image/upload/v1697220616/movie-app/tmp-5-1697220613691_r6v9fs.jpg"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Email or password not provided"
          },
          "500": { "$ref": "#/components/responses/ServerError" }
        }
      }
    },
    "/api/auth/user": {
      "get": {
        "tags": ["Users"],
        "summary": "User Details",
        "description": "Getting User Details",
        "responses": {
          "200": {
            "description": "User's id and image",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "id": {
                      "type": "string",
                      "example": "6516832f3bdaa5d3e07a4db5"
                    },
                    "image": {
                      "type": "string",
                      "example": "https://res.cloudinary.com/demmgc49v/image/upload/v1697220616/movie-app/tmp-5-1697220613691_r6v9fs.jpg"
                    }
                  }
                }
              }
            }
          },
          "401": { "$ref": "#/components/responses/UnauthorizedError" },
          "500": { "$ref": "#/components/responses/ServerError" }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "post": {
        "tags": ["Users"],
        "summary": "Update User",
        "description": "Updating User Details",
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Upload Successfull Message",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Profile Photo Updated!"
                    }
                  }
                }
              }
            }
          },
          "401": { "$ref": "#/components/responses/UnauthorizedError" },
          "500": { "$ref": "#/components/responses/ServerError" }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/api/movie": {
      "get": {
        "tags": ["Movies"],
        "summary": "All Movies",
        "description": "Getting All Movies",
        "responses": {
          "200": {
            "description": "All Movies",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "success"
                    },
                    "status": {
                      "type": "booleam",
                      "example": "true"
                    },
                    "data": {
                      "type": "object",
                      "example": [
                        {
                          "_id": "6565d1c4f42f243a3f9cb435",
                          "Title": "Avatar",
                          "Year": 2009,
                          "Rated": "PG-13",
                          "Rating": "7.9",
                          "Poster": "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
                          "Type": "movie",
                          "Image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
                          "BookmarkBy": ["6565d7305968803eb5163949"],
                          "createdAt": "2023-11-28T11:40:52.226Z",
                          "updatedAt": "2023-11-28T12:07:24.257Z",
                          "__v": 0
                        },
                        {
                          "_id": "6565d1c4f42f243a3f9cb436",
                          "Title": "I Am Legend",
                          "Year": 2007,
                          "Rated": "PG-13",
                          "Rating": "7.2",
                          "Poster": "http://ia.media-imdb.com/images/M/MV5BMTU4NzMyNDk1OV5BMl5BanBnXkFtZTcwOTEwMzU1MQ@@._V1_SX300.jpg",
                          "Type": "movie",
                          "Image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI0NTI4NjE3NV5BMl5BanBnXkFtZTYwMDA0Nzc4._V1_.jpg",
                          "BookmarkBy": [],
                          "createdAt": "2023-11-28T11:40:52.227Z",
                          "updatedAt": "2023-11-28T12:07:36.504Z",
                          "__v": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "500": { "$ref": "#/components/responses/ServerError" }
        }
      }
    },
    "/api/movie/{id}": {
      "get": {
        "tags": ["Movies"],
        "summary": "Single Movie",
        "description": "Getting A Single Movie",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "integer",
            "required": true,
            "description": "id of the movie to get",
            "schema": {
              "type": "string",
              "example": "6516832f3bdaa5d3e07a4db5"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Single Movie",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "success"
                    },
                    "status": {
                      "type": "booleam",
                      "example": "true"
                    },
                    "data": {
                      "type": "array",
                      "example": [
                        {
                          "_id": "6565d1c4f42f243a3f9cb435",
                          "Title": "Avatar",
                          "Year": 2009,
                          "Rated": "PG-13",
                          "Rating": "7.9",
                          "Poster": "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
                          "Type": "movie",
                          "Image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
                          "BookmarkBy": ["6565d7305968803eb5163949"],
                          "createdAt": "2023-11-28T11:40:52.226Z",
                          "updatedAt": "2023-11-28T12:07:24.257Z",
                          "__v": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "No Movie with the provided ID",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "failed"
                    },
                    "status": {
                      "type": "booleam",
                      "example": "false"
                    },
                    "data": {
                      "type": "string",
                      "example": "No Movie with ID:6565d1c4f42f243a3f9cb435"
                    }
                  }
                }
              }
            }
          },
          "500": { "$ref": "#/components/responses/ServerError" }
        }
      }
    },
    "/api/bookmark": {
      "get": {
        "tags": ["Bookmarks"],
        "summary": "Bookmarks",
        "description": "Get all user bookmarks",
        "responses": {
          "200": {
            "description": "Single Movie",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "success"
                    },
                    "status": {
                      "type": "booleam",
                      "example": "true"
                    },
                    "data": {
                      "type": "array",
                      "example": [
                        {
                          "_id": "6565d1c4f42f243a3f9cb435",
                          "Title": "Avatar",
                          "Year": 2009,
                          "Rated": "PG-13",
                          "Rating": "7.9",
                          "Poster": "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
                          "Type": "movie",
                          "Image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
                          "BookmarkBy": ["6565d7305968803eb5163949"],
                          "createdAt": "2023-11-28T11:40:52.226Z",
                          "updatedAt": "2023-11-28T12:07:24.257Z",
                          "__v": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "No Movie with the provided ID",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "failed"
                    },
                    "status": {
                      "type": "booleam",
                      "example": "false"
                    },
                    "data": {
                      "type": "string",
                      "example": "No Movie with ID:6565d1c4f42f243a3f9cb435"
                    }
                  }
                }
              }
            }
          },
          "500": { "$ref": "#/components/responses/ServerError" }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "name": "Token",
        "scheme": "bearer",
        "in": "header"
      }
    },
    "responses": {
      "UnauthorizedError": {
        "description": "Invalid Token, Missing Token or Token doesn't start with Bearer",
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Unauthorized"
                }
              }
            }
          }
        }
      },
      "ServerError": {
        "description": "Server Error",
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Something went wrong, try again later"
                }
              }
            }
          }
        }
      },
      "MethodNotAllowed": {
        "description": "Method Not Allowed",
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Method not allowed"
                }
              }
            }
          }
        }
      }
    },
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string",
            "example": "Jacob"
          },
          "email": {
            "type": "string",
            "example": "JacobIsaac@gmail.com"
          },
          "password": {
            "type": "string",
            "example": "007007"
          }
        }
      }
    }
  }
}
